[package]
name = "otelcol-rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
otel-deltalake-exporter = { path = "../../crates/otel-deltalake-exporter" }
otel-arrow-dfe = { path = "../../submodules/otel-arrow/rust/otap-dataflow", default-features = false, features = ["otlp", "parquet", "crypto-ring"] }

[lints]
workspace = true
