services:
  workspace:
    image: ghcr.io/mdrakiburrahman/rust-playground/devcontainer:d84da0b0dffa796063b6748360647001c3b29521c0c547dcf4f4faf6d7b5a2fd
    command: sleep infinity
    init: true
    volumes:
      - type: bind
        source: ..
        target: /workspaces/rust-playground
        consistency: cached
      - type: bind
        source: ${HOST_AZURE_DIR:?Run the devcontainer initializeCommand first}
        target: /home/vscode/.azure
        read_only: false
      - type: bind
        source: ${HOST_GH_CONFIG_DIR:?Run the devcontainer initializeCommand first}
        target: /home/vscode/.config/gh
        read_only: false
      - type: volume
        source: node_modules
        target: /workspaces/rust-playground/node_modules
      - type: volume
        source: nx_cache
        target: /workspaces/rust-playground/.nx
      - type: volume
        source: rust_target
        target: /workspaces/rust-playground/target

volumes:
  node_modules:
  nx_cache:
  rust_target:
